version: '3'
services:
  db:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
    volumes:
      - 'sql:/bitnami'
    restart: on-failure
  php-fpm:
    image: 'shingo0620/php:${PHP_VERSION}-fpm'
    volumes:
    - ./src:/var/www/html:cached
    depends_on:
      - db
    restart: on-failure
  web:
    image: pagespeed/nginx-pagespeed
    ports:
      - '80'
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/certs
      - ./src:/var/www/html
    depends_on:
      - php-fpm
    restart: on-failure
  src:
    build: ./src
    image: ${PROJECT}:${VERSION}
    volumes:
      - './src:/var/www/html'
    tty: true
volumes:
  sql: